services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    CodeRhapsodie\ConnectorGemini\ClientProvider: ~

    CodeRhapsodie\Contracts\ConnectorGemini\ClientProviderInterface:
        '@CodeRhapsodie\ConnectorGemini\ClientProvider'
