services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    CodeRhapsodie\Bundle\ConnectorGemini\Form\Type\:
        resource: '../../Form/Type'
        tags:
            - { name: form.type }

    CodeRhapsodie\Bundle\ConnectorGemini\Form\Type\TextToTextOptionsType:
        arguments:
            $models: '%cr.connector_gemini.text_to_text.models%'
            $defaultModel: '%cr.connector_gemini.text_to_text.default_model%'
            $defaultTemperature: '%cr.connector_gemini.text_to_text.default_temperature%'
            $defaultMaxTokens: '%cr.connector_gemini.text_to_text.default_max_tokens%'
        tags:
            - { name: form.type }

    CodeRhapsodie\Bundle\ConnectorGemini\Form\Type\ImageToTextOptionsType:
        arguments:
            $models: '%cr.connector_gemini.image_to_text.models%'
            $defaultModel: '%cr.connector_gemini.image_to_text.default_model%'
            $defaultTemperature: '%cr.connector_gemini.image_to_text.default_temperature%'
            $defaultMaxTokens: '%cr.connector_gemini.image_to_text.default_max_tokens%'
        tags:
            - { name: form.type }

    ibexa.connector_ai.action_configuration.handler.gemini_image_to_text.form_mapper.options:
        class: Ibexa\Bundle\ConnectorAi\Form\FormMapper\ActionConfiguration\ActionHandlerOptionsFormMapper
        arguments:
            $formType: 'CodeRhapsodie\Bundle\ConnectorGemini\Form\Type\ImageToTextOptionsType'
        tags:
            -   name: ibexa.connector_ai.action_configuration.form_mapper.options
                type: gemini-image-to-text

    ibexa.connector_ai.action_configuration.handler.gemini_text_to_text.form_mapper.options:
        class: Ibexa\Bundle\ConnectorAi\Form\FormMapper\ActionConfiguration\ActionHandlerOptionsFormMapper
        arguments:
            $formType: 'CodeRhapsodie\Bundle\ConnectorGemini\Form\Type\TextToTextOptionsType'
        tags:
            -   name: ibexa.connector_ai.action_configuration.form_mapper.options
                type: gemini-text-to-text
